.\" Manpage for gotoc
.\" Contact <contact@efrits.fr> to correct errors or typos.
.TH GOTOC 1 "Octobre 2025" "EFRITS" "Interprète de langage"

.SH NOM
gotoc \- 

.SH SYNOPSIS
.B gotoc
[\fIOPTIONS\fR] [\fIARGUMENTS\fR]

.SH DESCRIPTION
.PP
Ce manuel est un placeholder pour le manuel qui devra décrire la commande
.B gotoc
.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Affiche un message d’aide et quitte.
.TP
\fB\-v\fR, \fB\-\-version\fR
Affiche la version du programme et quitte.

.SH EXEMPLES
.PP
.TP
.B gotoc
Exemple d’appel sans argument.
.TP
.B gotoc \-\-help
Affiche l’aide.

.SH FICHIERS
.PP
\fI/etc/gotoc.conf\fR \- fichier de configuration par défaut (s’il existe)

.SH VARIABLES D'ENVIRONNEMENT
.PP
Aucune variable d’environnement spécifique n’est actuellement utilisée.

.SH CODES DE SORTIE
.PP
.TP
0
Succès.
.TP
Autre
Erreur d’exécution.

.SH BOGUES
.PP
Signalez les bogues à <contact@efrits.fr>.

.SH AUTEUR
.PP
Rédigé par Jason Brillante "Damdoshi".

.SH COPYRIGHT
.PP
Licence libre (GNU GPL).

.SH VOIR AUSSI
.BR bash (1),
.BR man (1)
